name: Push to Portfolio Content Directory

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: "Read file contents"
        uses: lucaengelhard/portfolio-readme-parse-action@v1.1
        with:
          path: "README.md"
