name: Push to Portfolio Content Directory

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  create-readme-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Read file contents"
        id: read_file
        uses: lucaengelhard/portfolio-readme-parse-action@v1.1
        with:
          path: "README.md"
      - name: Create target file
        run: echo "${{ steps.read_file.outputs.markdown }}" > ${{ github.event.repository.name }}.md
      - name: show that file exists
        run: ls
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v4
        with:
          repository: lucaengelhard/portfolio
          ref: main
      - name: Copy Generated MD File
        run: cp ${{ github.event.repository.name }}.md content/
      - name: add changes
        run: git add .
      - name: commit
        run: git commit -m "Adding or Updating ${{ github.event.repository.name }} to content directory"
      - name: push
        run: gh pr create
