name: Push to Portfolio Content Directory

on:
  push:
    branches: "main"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.TOKEN_TO_ACCESS_OUTPUT_REPO }}

jobs:
  create-readme-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Read file contents"
        id: read_file
        uses: lucaengelhard/portfolio-readme-parse-action@v1.3
        with:
          path: "README.md"
          title: "${{ github.event.repository.name }}"
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v4
        with:
          repository: lucaengelhard/portfolio
          ref: main
          token: ${{ secrets.TOKEN_TO_ACCESS_OUTPUT_REPO }}
      - name: Create target file
        run: echo "${{ steps.read_file.outputs.markdown }}" > content/${{ github.event.repository.name }}.md
      - run: |
          git config --global user.email "me@lucaengelhard.com"
          git config --global user.name "Luca Engelhard"
          git checkout -b ${{ github.event.repository.name }}-readme
          git add .
          git commit -m "Adding or Updating ${{ github.event.repository.name }} to content directory"
          git push -f --set-upstream origin ${{ github.event.repository.name }}-readme
          gh pr create --fill
