name: "🚀 publish npm"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.1.1
      - name: 🚀 publish
        run: npm publish --access private
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
