name: Publish to JSR
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - run: npm install
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
