name: Publish to JSR
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
