name: Readme Transfer

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [main]
    paths:
      - "README.md" # limit trigger to the target-filepath.
        # It's not elegant to set same value in two options but
        # there is no way to retrieve this value in composite action.

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: sator-imaging/Copy-to-Another-Repository@v1
        with:
          # required parameters
          target-filepath: "content/ao3-toolkit.md" # file path to copy
          output-branch: "main" # branch name to create pull request
          output-repo: "lucaengelhard/portfolio"
          git-token: ${{ secrets.TOKEN_TO_ACCESS_OUTPUT_REPO }}
